**Задание на повторение материала
    1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
    2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
    3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
    4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
    5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
    6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
    7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
    8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
    9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
    10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
    11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.
    12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
    13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(1, 12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a.reshape(-1, 12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: нет

In [13]:
b = a.reshape(12, 1)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
b.ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
c = np.random.randn(3, 4)
print(c)

[[-1.06099934 -0.1934577  -0.89367934  0.77644785]
 [-0.21149536  0.28020205 -1.18513735  0.61050732]
 [ 0.64699903 -0.83737537 -0.97432748 -0.35092233]]


In [16]:
d = c.flatten()
print(d)

[-1.06099934 -0.1934577  -0.89367934  0.77644785 -0.21149536  0.28020205
 -1.18513735  0.61050732  0.64699903 -0.83737537 -0.97432748 -0.35092233]


In [17]:
c.size == d.size

True

 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [19]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [20]:
np.array_equal(a, b)

True

Ответ: Никакой разницы между массивами a и b нет.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [21]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print(f'Массив a:\n {a}')
print(f'Массив b:\n {b}')

Массив a:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив b:
 [[1. 1.]
 [1. 1.]]


In [22]:
v = np.vstack((a, b))
print(v)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [23]:
v.size

10

 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [24]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [27]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [28]:
print(f'Размер матрицы В: {B.size}')

Размер матрицы В: 16


In [30]:
B_inv = np.linalg.inv(B)
print(B_inv)

LinAlgError: Singular matrix

Попытка найти определитель матрицы В:

In [31]:
np.linalg.det(B)

0.0

Ответ: Вычисление обратной матрицы В невозможно, т.к. её определитель равен нулю, следовательно она является сингулярной или вырожденной квадратичной матрицей.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [32]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [43]:
c = np.random.randint(0, high=16, size=16)
print(c)

[11  6  8  7 11  1  0 15  6  6 13  7  4  2 11  7]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [44]:
np.sqrt(c.size)

4.0

In [54]:
C = np.reshape(c, (4, 4))
print(C)

[[11  6  8  7]
 [11  1  0 15]
 [ 6  6 13  7]
 [ 4  2 11  7]]


In [55]:
D = B + (C * 10)
print(D)

[[115  74 103 102]
 [124  60  86 272]
 [ 83 146 279 282]
 [ 72 142 322 372]]


In [56]:
print(f'Определитель матрицы D: {np.linalg.det(D)}')

Определитель матрицы D: 82810800.0000002


In [57]:
print(f'Ранг матрицы D: {np.linalg.matrix_rank(D)}')

Ранг матрицы D: 4


In [58]:
D_inv = np.linalg.inv(D)
print(f'Обратная матрица D_inv для D:\n {D_inv}')

Обратная матрица D_inv для D:
 [[ 0.01887628 -0.00296338 -0.0206432   0.0126399 ]
 [-0.0302661   0.01305772  0.06866302 -0.05329981]
 [ 0.01788945 -0.01193612 -0.02999416  0.02655982]
 [-0.00758524  0.00592097  0.00374806 -0.00240259]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [59]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0

In [60]:
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
print(D_inv)

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]


In [62]:
E = np.where(D_inv, B, C)
print(E)

[[  5   6   8  32]
 [ 11  50  86  15]
 [ 23   6  13 212]
 [  4 122 212   7]]
